project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    code-fold: true
  docx: default


bibliography: references.bib
csl: vancouver.csl

crossref:
  custom:
    - kind: float
      key: supptbl
      reference-prefix: "Table S"
      caption-prefix: "Table S"
      space-before-numbering: false
      caption-location: top
